Repository insight-LINK/insightLINK, pull requests merged in 2023-06, with the labels that each got.

#25 [FE] 그래프 클릭 시 상태 변경 기능 구현
  client/src/axios/dashBoardApi.tsx
  client/src/components/dashboard/Card.tsx
  client/src/components/dashboard/CardPanel.tsx
  client/src/components/dashboard/MainGraph.tsx
  client/src/components/dashboard/SearchBar.tsx
  client/src/components/dashboard/UseInfo.tsx
  client/src/components/dashboard/UserPanel.tsx
  client/src/pages/dashboard.tsx
Labels: FE, 기능추가, 레이아웃

#26 [FE] 대쉬보드 페이지 타입 에러 수정
  client/src/components/dashboard/MainGraph.tsx
  client/src/components/dashboard/SearchBar.tsx
  client/src/components/dashboard/UseInfo.tsx
Labels: FE, 수정

#29 [FE] 사진 업로드 모달 추가
  client/src/components/dashboard/ImgUploadBtn.tsx
  client/src/components/dashboard/UserPanel.tsx
  client/src/components/image/ImageUpload.tsx
  client/src/components/social/CardDetail.tsx
  client/src/components/social/Feeds.tsx
  client/src/components/social/Friends.tsx
  client/src/pages/dashboard.tsx
Labels: FE, 기능추가, 레이아웃

#33 [BE] 로그인 기능 병합
  client/src/axios/POST.tsx
  client/src/components/LoginButton.tsx
  client/src/components/UseronlyButton.tsx
  client/src/components/image/ImageUpload.tsx
  client/src/setupProxy.js
  server/db/graphQueries.js
  server/dbconfig.js
  server/index.js
  server/middlewares/auth-middleware.js
  server/routes/graphs.js
  server/routes/login.js
  server/routes/test.js
  server/routes/uploads.js
  server/services/taglist.js
Labels: BE, 기능추가, 리펙토링

#35 [공통] 그래프 api 연동 및 로그인 기능 통합
  client/src/axios/dashBoardApi.tsx
  client/src/pages/dashboard.tsx
  server/db/graphQueries.js
  server/index.js
  server/middlewares/auth-middleware.js
  server/routes/graphs.js
  server/routes/uploads.js
Labels: FE, BE, 기능추가, 에러 핸들링, 수정

#36 [BE] 그래프 쿼리 수정
  client/src/components/LoginButton.tsx
  server/routes/graphs.js
Labels: BE, 리펙토링, 수정

#41 [FE/BE] 일반 로그인 로그아웃 기능 구현
  client/src/components/LogoutBtn.tsx
  client/src/components/UserModal.tsx
  client/src/pages/dashboard.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
  server/routes/login.js
  server/routes/signup.js
Labels: FE, BE, 기능추가

#44 [BE] 유저 조회 & 프로필 조회
  server/db/userQueries.js
  server/index.js
  server/routes/user.js
Labels: BE, 기능추가

#46 [FE] 유저 프로필 조회 API 추가
  client/src/axios/GET.tsx
  client/src/axios/POST.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/User/NavBar.tsx
  client/src/pages/dashboard.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
Labels: FE, 기능추가, 레이아웃

#47 [FE] 전체 디자인 수정
  client/db.json
  client/src/features/Dashboard/components/SearchBar.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/ImageUpload/ImgList.tsx
  client/src/features/Search/ContentSearch.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/User/LoginButton.tsx
  client/src/pages/index.tsx
  client/src/pages/search.tsx
  client/src/pages/social.tsx
  client/src/styles/wrapper.tsx
  client/src/types/social.types.tsx
Labels: FE, 레이아웃

#49 feat: 클릭한 태그 관련 카드조회
  server/index.js
  server/routes/cards.js
  server/routes/graphs.js
  server/routes/test.js
Labels: BE, 기능추가

#53 [BE] 태그 병합
  server/index.js
  server/routes/tag.js
  server/routes/user.js
Labels: BE, 기능추가

#55 [FE] 태그 병합
  client/src/features/Dashboard/components/MainGraph.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/MainGraph/components/Interaction/CombineNode.tsx
  server/db/graphQueries.js
Labels: FE, 기능추가

#57 [FE] 태그 인터랙션 추가
  client/src/features/Dashboard/components/MainGraph.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/MainGraph/components/Interaction/AnimateCombineNodes.tsx
  client/src/features/MainGraph/components/Interaction/CombineNode.tsx
  client/src/types/imgUpload.types.tsx
  server/routes/graphs.js
Labels: FE, 기능추가

#59 [FE] 검색 결과 갯수
  client/src/pages/search.tsx
  server/index.js
Labels: FE

#61 [BE] 태그병합
  client/src/features/Dashboard/components/MainGraph.tsx
  client/src/features/User/LoginButton.tsx
  server/db/userQueries.js
  server/index.js
  server/routes/myInfo.js
  server/routes/tag.js
  server/routes/user.js
Labels: BE, 에러 핸들링

#62 [BE] 태그관련 카드조회, 카드상세, 카드복제 기능 추가
  server/db/cardQueries.js
  server/db/graphQueries.js
  server/db/tagQueries.js
  server/db/userQueries.js
  server/index.js
  server/middlewares/cardCopy.js
  server/middlewares/cardInfo.js
  server/middlewares/cardTag.js
  server/routes/cards.js
  server/routes/graphs.js
  server/routes/test.js
  server/routes/uploads.js
  server/routes/user.js
Labels: BE, 기능추가, 리펙토링

#63 [FE] 대시 보드 페이지 그래프 클릭이벤트 오류 수정
  client/db.json
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/components/Card.tsx
  client/src/features/Dashboard/components/CardPanel.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/MainCard/components/Card.tsx
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/features/MainCard/hook/useCard.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/components/MainGraph/MainGraph.tsx
  client/src/features/MainGraph/hooks/useResizeGraph.tsx
  client/src/pages/_app.tsx
  client/src/pages/dashboard.tsx
  client/src/pages/login.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
Labels: FE, 기능추가, 에러 핸들링

#64 [FE] 태그 병합 충돌 해결
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/components/MainGraph.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/components/Interaction/AnimateCombineNodes.tsx
  client/src/features/MainGraph/components/Interaction/CombineNode.tsx
  client/src/types/graph.types.tsx
  client/src/types/imgUpload.types.tsx
Labels: FE, 리펙토링, 에러 핸들링

#65 [Fix Error] Fix searchRouter Error
  server/index.js
Labels: 에러 핸들링

#66 [FE] 빌드 에러 해결
  client/src/axios/dashBoardApi.tsx
  client/src/features/MainCard/components/Card.tsx
  client/src/features/MainCard/hook/useCard.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/User/LoginButton.tsx
  client/src/pages/search.tsx
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
Labels: FE, 에러 핸들링

#67 [FE] refactoring, 빈 공간 클릭 시 발생하는 에러 처리
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/components/Interaction/AnimateCombineNodes.tsx
  client/src/features/MainGraph/components/OnClickEvent/MouseDown.tsx
  client/src/features/MainGraph/components/OnClickEvent/MouseUp.tsx
Labels: FE, 리펙토링, 에러 핸들링

#69 [FE/BE] NextAuth 이용한 구글 소셜 로그인
  README.md
  client/package.json
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/User/GoogleLoginBtn.tsx
  client/src/features/User/GoogleLogoutBtn.tsx
  client/src/features/User/LoginBtn.tsx
  client/src/features/User/LoginButton.tsx
  client/src/features/User/LogoutButton.tsx
  client/src/features/User/SignupButton.tsx
  client/src/features/User/UserModal.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/logout.tsx
  server/routes/login.js
Labels: FE, BE, 에러 핸들링, 수정

#70 [BE] DB 변경에 따른 쿼리수정
  server/db/cardQueries.js
  server/db/searchQueries.js
  server/db/userQueries.js
  server/index.js
  server/middlewares/cardCopy.js
  server/routes/search.js
  server/routes/uploads.js
Labels: BE, 수정

#73 [BE] 태그병합
  server/index.js
  server/routes/tag.js
Labels: BE, 에러 핸들링, 수정

#82 [FE/BE] 모달창 마이페이지 닉네임 수정
  client/src/features/User/UserModal.tsx
  server/index.js
  server/routes/mypage.js
Labels: FE, BE, 기능추가

#83 [FE] uri, 헤더 토큰 수정
  client/src/axios/getToken.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/MainGraph/components/OnClickEvent/MouseDown.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
Labels: FE, 리펙토링

#85 [BE] 그래프조회
  server/routes/graphs.js
Labels: BE, 리펙토링

#88 [FE] 대시보드 그래프, 유저 정보 수정
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/components/UseInfo.tsx
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/components/OnClickEvent/MouseDown.tsx
Labels: FE, 수정

#89 feat: 소셜 기능 추가
  server/db/followQueries.js
  server/db/socialQueries.js
  server/index.js
  server/middlewares/cardInfo.js
  server/middlewares/follow.js
  server/middlewares/recomCard.js
  server/middlewares/recomUser.js
  server/routes/social.js
Labels: BE, 기능추가

#92 [BE] 그래프 조회
  client/package-lock.json
  server/routes/graphs.js
Labels: BE, 리펙토링, 에러 핸들링

#93 [FE/BE] Add 알림바, 탈퇴버튼 - #81
  README.md
  client/src/features/User/GoogleLogoutBtn.tsx
  client/src/features/User/SwithToggle.tsx
  client/src/features/User/UserModal.tsx
  client/src/features/User/WithdrawalBtn.tsx
  client/src/pages/index.tsx
  server/routes/login.js
  server/routes/mypage.js
Labels: FE, BE, 기능추가, 에러 핸들링

#94 [FE] 소셜 페이지 API 수정 및 추가
  client/src/axios/getToken.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/components/OnClickEvent/MouseDown.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
  client/src/types/social.types.tsx
Labels: FE, 기능추가

#95 [FE] 그래프 카테고리(연결요소별 색 변경) 추가
  client/db.json
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 기능추가

#97 [BE] fix: 카드상세 조회 수정
  server/db/cardQueries.js
  server/middlewares/cardInfo.js
Labels: BE, 수정

#98 [BE] 그래프 조회
  server/routes/graphs.js
Labels: BE, 기능추가

#101 [BE] graph 쿼리 들여쓰기 수정
  server/db/graphQueries.js
Labels: BE, 리펙토링

#103 [BE] 프로필 조회
  server/routes/user.js
Labels: BE, 기능추가

#106 [FE/BE] 검색 페이지네이션 수정
  README.md
  client/src/pages/search.tsx
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
  server/routes/search.js
Labels: FE, BE, 수정

#107 [FE] 설정 모달창 최상단 노출 버그 수정
  client/src/features/Dashboard/components/NavBar.tsx
Labels: FE, 에러 핸들링

#110 [FE] 검색 결과 하이라이팅
  client/src/features/Search/ContentSearch.tsx
  client/src/pages/search.tsx
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
Labels: FE, 기능추가

#112 [BE] 카드수정
  server/middlewares/cardUpdate.js
  server/routes/cards.js
Labels: BE, 기능추가

#108 [FE] 업로드 완료 시 이미지 업로드 모달 닫기 예외 처리 추가
  client/src/features/ImageUpload/ImageUpload.tsx
Labels: FE, 수정

#113 [FE] 빌드 타입 에러 수정
  client/src/features/Dashboard/components/UserInfo.tsx
  client/src/features/Dashboard/components/UserPanel.tsx
  client/src/features/MainCard/components/Card.tsx
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 에러 핸들링

#116 [BE] 카드삭제
  server/middlewares/cardDelete.js
  server/routes/cards.js
Labels: BE, 기능추가

#117 [FE] 카드 수정
  client/src/features/MainCard/components/Card.tsx
  server/middlewares/cardUpdate.js
Labels: FE, 기능추가

#118 [FE] 카드 상세 페이지 추가 - #3
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/types/social.types.tsx
Labels: FE, 기능추가, 레이아웃

#119 [FE] 충돌 수정
  client/src/axios/dashBoardApi.tsx
  client/src/features/MainCard/components/CardDetail.tsx
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/features/MainCard/hook/useCard.tsx
  client/src/features/MainCard/hook/useDetail.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/hooks/useGraph.tsx
  client/src/pages/dashboard/[userid].tsx
  client/src/pages/dashboard/index.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 수정

#120 [FE] 빌드 에러 수정
  client/src/axios/dashBoardApi.tsx
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/features/MainCard/hook/useCard.tsx
  client/src/features/MainGraph/hooks/useGraph.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/User/GoogleLogoutBtn.tsx
  client/src/pages/dashboard/[userid].tsx
  client/src/pages/logout.tsx
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
  client/src/types/dashborad.types.tsx
  client/src/types/social.types.tsx
Labels: FE, 수정

#121 [FE] 빌드 에러 수정
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/components/UserInfo.tsx
  client/src/features/MainCard/components/Card.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/types/dashborad.types.tsx
  client/src/types/social.types.tsx
Labels: FE, 배포, 수정

#123 fix: 친구추천 수정
  server/db/socialQueries.js
  server/middlewares/cardCopy.js
  server/middlewares/cardInfo.js
  server/middlewares/cardTag.js
  server/middlewares/recomUser.js
Labels: BE, 수정

#124 [FE] 카드 복제 버튼 추가
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
Labels: FE

#125 [FE] 빌드 오류 수정
  client/src/features/MainCard/components/CardPanel.tsx
Labels: FE, 에러 핸들링

#127 [QA] 로그인, 회원가입
  client/src/features/User/LogoutBtn.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
  server/routes/login.js
  server/routes/signup.js
Labels: FE, BE, 에러 핸들링

#129 [QA] 검색기능
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
  server/routes/search.js
Labels: FE, BE, 에러 핸들링

#131 [BE] 로그인 유저 아이디 전달
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  server/routes/login.js
Labels: FE, BE, 수정

#133 [BE] fix: 추천카드 로직 변경
  server/db/socialQueries.js
  server/middlewares/recomCard.js
  server/routes/cards.js
Labels: BE, 수정

#134 [BE] fix: redis 오류 수정
  client/package.json
  server/middlewares/recomCard.js
  server/middlewares/recomUser.js
  server/package.json
  server/routes/graphs.js
  server/routes/uploads.js
  server/services/taglist.js
Labels: BE, 수정

#136 [FE] 이미지 S3에 업로드 후 링크 서버에 전송 추가
  client/next.config.js
  client/package.json
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/types/imgUpload.types.tsx
Labels: FE, 리펙토링

#137 [BE] fix: 이미지 업로드 수정
  client/src/features/ImageUpload/ImageUpload.tsx
  server/routes/uploads.js
Labels: BE, 수정

#138 [FE] 대시보드 카드 디테일 기능 수정
  client/src/axios/dashBoardApi.tsx
  client/src/features/MainCard/components/Card.tsx
  client/src/features/MainCard/components/CardDetail.tsx
  client/src/features/MainCard/hook/useDetail.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/recoil/atoms/LoginStateAtom.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 수정

#139 [FE] 대시보드 그래프 로그인 상태에 따른 버튼 활성화 기능
  client/src/axios/dashBoardApi.tsx
  client/src/features/MainCard/components/Card.tsx
  client/src/features/MainCard/components/CardDetail.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/recoil/atoms/LoginStateAtom.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 기능추가

#140 [FE] 팔로잉 피드와 추천 피드 구분
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
Labels: FE, 기능추가

#141 [FE] 이미지 리사이징(canvas)
  client/src/features/ImageUpload/ImageUpload.tsx
Labels: FE, 기능추가

#144 [FE]내 그래프 공유하기
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/pages/_app.tsx
Labels: FE, 기능추가

#147 [FE] 그래프 수정
  client/.gitignore
  client/package.json
  client/src/features/MainGraph/components/Graph/Graph.tsx
Labels: FE, 기능추가, 수정

#150 [BE] 다른사람 정보 조회
  client/package-lock.json
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/graphs.js
  server/routes/notification.js
  server/routes/user.js
Labels: BE, 기능추가

#151 [BE] 내 그래프에 다른 사람 카드 복제(소셜)
  server/db/cardQueries.js
  server/middlewares/cloneCard.js
  server/routes/social.js
Labels: BE, 기능추가

#152 [FE] 내 그래프에 다른 사람의 카드 추가 API 추가 - #3
  client/src/features/Social/components/CardDetail.tsx
Labels: FE, 기능추가

#158 [FE] legend(category) 번호 밀림 버그 수정
  client/src/features/MainGraph/components/Graph/Graph.tsx
  server/routes/graphs.js
Labels: FE, 수정

#159 [FE] 이미지 업로드 시 로딩창 추가
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/MainGraph/components/Loading/GraphLoading.tsx
  client/src/features/MainGraph/components/Loading/UploadLoading.tsx
  client/src/pages/dashboard/[userid].tsx
  client/src/pages/dashboard/index.tsx
Labels: FE, 기능추가, 레이아웃

#162 [BE] 디버깅용 log 기록
  server/.gitignore
  server/middlewares/cardCopy.js
  server/middlewares/cardDelete.js
  server/middlewares/cardInfo.js
  server/middlewares/cardTag.js
  server/middlewares/cardUpdate.js
  server/middlewares/cloneCard.js
  server/middlewares/follow.js
  server/middlewares/recomCard.js
  server/middlewares/recomUser.js
  server/package.json
  server/routes/graphs.js
  server/routes/login.js
  server/routes/mypage.js
  server/routes/notification.js
  server/routes/search.js
  server/routes/signup.js
  server/routes/tag.js
  server/routes/uploads.js
  server/routes/user.js
  server/winston.js
  server/winston/logger.js
Labels: BE, 에러 핸들링

#164 [BE] fix: logger error - #161
  server/middlewares/cardUpdate.js
  server/middlewares/cloneCard.js
Labels: BE, 에러 핸들링

#166 [FE]fix: logoutBtn router move
  client/src/features/User/LogoutBtn.tsx
Labels: FE, 에러 핸들링

#167 [FE] 이미지 업로드 모달, 로딩페이지 디자인 수정
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/ImageUpload/ImgList.tsx
  client/src/features/MainGraph/components/Loading/UploadLoading.tsx
  client/src/pages/dashboard/index.tsx
  client/src/styles/wrapper.tsx
Labels: FE, 기능추가, 레이아웃

#169 [BE] 업로드 코드 리팩토링 및 더미데이터 생성코드
  server/db/graphQueries.js
  server/index.js
  server/routes/graphs.js
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/test.js
Labels: BE, 기능추가, 수정

#171 [BE] 유저 프로필 조회
  client/package-lock.json
  server/db/userQueries.js
  server/index.js
  server/middlewares/otherInfo.js
  server/middlewares/userInfo.js
  server/middlewares/userProfile.js
  server/routes/other.js
  server/routes/user.js
Labels: BE, 기능추가, 에러 핸들링, 수정

#173 [BE] logger
  server/middlewares/userProfile.js
  server/package.json
Labels: BE, 기능추가

#175 [BE] 유저정보조회 수정
  server/db/userQueries.js
  server/middlewares/otherInfo.js
  server/middlewares/userInfo.js
Labels: BE, 수정

#176 [FE] setCategories, chart options code spliting
  client/src/features/MainGraph/components/Graph/ChartDefaultOptions.tsx
  client/src/features/MainGraph/components/Graph/Graph.tsx
  client/src/features/MainGraph/components/Graph/setCategories.tsx
Labels: FE, 리펙토링

#177 [FE] 이미지 업로드 기존 props 사용 => recoil 사용 수정
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/MainGraph/components/Loading/UploadLoading.tsx
  client/src/features/Social/components/Users.tsx
  client/src/pages/dashboard/index.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
Labels: FE, 리펙토링, 에러 핸들링

#179 [BE] 회원가입 후, 유저 정보 오류 - #178
  server/db/userQueries.js
  server/middlewares/userInfo.js
Labels: BE, 에러 핸들링

#181 [BE] 다른사람 정보 조회
  server/middlewares/otherInfo.js
Labels: BE, 수정

#182 [FE] 병합 시 간선이 모두 끊기는 문제 수정
  client/src/features/MainGraph/components/Interaction/AnimateCombineNodes.tsx
  client/src/features/MainGraph/components/OnClickEvent/MouseDown.tsx
Labels: FE, 기능추가

#190 [FE] 대시보드 레이아웃 수정, 리펙토링
  client/next.config.js
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Dashboard/MainCard/components/CardDetail.tsx
  client/src/features/Dashboard/MainCard/components/CardPanel.tsx
  client/src/features/Dashboard/MainCard/hook/useCard.tsx
  client/src/features/Dashboard/MainCard/hook/useDetail.tsx
  client/src/features/Dashboard/MainCard/hook/useGetCardData.tsx
  client/src/features/Dashboard/MainGraph/components/Graph/ChartDefaultOptions.tsx
  client/src/features/Dashboard/MainGraph/components/Graph/Graph.tsx
  client/src/features/Dashboard/MainGraph/components/Graph/setCategories.tsx
  client/src/features/Dashboard/MainGraph/components/Interaction/AnimateCombineNodes.tsx
  client/src/features/Dashboard/MainGraph/components/Interaction/CombineNode.tsx
  client/src/features/Dashboard/MainGraph/components/Loading/GraphLoading.tsx
  client/src/features/Dashboard/MainGraph/components/Loading/UploadLoading.tsx
  client/src/features/Dashboard/MainGraph/components/MainGraph/MainGraph.tsx
  client/src/features/Dashboard/MainGraph/components/OnClickEvent/MouseDown.tsx
  client/src/features/Dashboard/MainGraph/components/OnClickEvent/MouseUp.tsx
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  client/src/features/Dashboard/UserPanal/UserPanel.tsx
  client/src/features/Dashboard/UserPanal/components/FollowBtn.tsx
  client/src/features/Dashboard/UserPanal/components/UserInfo.tsx
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/MainCard/components/CardPanel.tsx
  client/src/features/MainGraph/components/MainGraph/MainGraph.tsx
  client/src/features/MainGraph/hooks/useResizeGraph.tsx
  client/src/pages/dashboard/[userid].tsx
  client/src/pages/dashboard/index.tsx
  client/src/pages/login.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
  client/src/styles/dashboard.css
  client/src/styles/globals.css
  client/src/styles/wrapper.tsx
  client/src/types/dashborad.types.tsx
  client/tailwind.config.js
Labels: FE, 기능추가, 레이아웃, 리펙토링

#194 [FE] 병합 및 빌드 오류 수정
  client/src/features/Dashboard/MainGraph/components/Graph/Graph.tsx
  client/src/features/Dashboard/MainGraph/components/MainGraph/MainGraph.tsx
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/pages/dashboard/index.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 리펙토링, 에러 핸들링, 수정

#195 [FE/BE] 검색 기능
  client/src/features/Search/Card.tsx
  client/src/features/Search/SearchBar.tsx
  client/src/pages/search.tsx
  client/src/pages/signup.tsx
  server/db/searchQueries.js
  server/index.js
  server/routes/search.js
  server/services/taglist.js
Labels: FE, BE, 기능추가

#198 [FE] 대시보드 유저 정보 css 수정
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Dashboard/MainCard/components/CardDetail.tsx
  client/src/features/Dashboard/MainCard/components/CardPanel.tsx
  client/src/features/Dashboard/MainGraph/components/Graph/Graph.tsx
  client/src/features/Dashboard/UserPanal/UserPanel.tsx
  client/src/features/Dashboard/UserPanal/components/GraphEditBtn.tsx
  client/src/features/Dashboard/UserPanal/components/SearchBar.tsx
  client/src/features/Dashboard/UserPanal/components/UserInfo.tsx
  client/src/features/hooks/useIsLogin.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
  client/src/styles/dashboard.css
  client/src/styles/globals.css
Labels: FE, 기능추가, 레이아웃

#204 [FE] 오타 및 변경 사항 수정
  client/src/pages/signup.tsx
  server/db/socialQueries.js
Labels: FE, BE, 에러 핸들링

#205 [BE] 추천피드 이미지로 변경
  server/db/socialQueries.js
  server/middlewares/recomCard.js
Labels: BE, 수정

#206 [FE]
  client/package.json
  client/src/features/Search/Card.tsx
  client/src/features/Search/CardModal.tsx
  client/src/pages/search.tsx
  client/src/pages/searchContent.tsx
  client/src/pages/searchTag.tsx
  server/db/searchQueries.js
  server/routes/search.js
Labels: FE, BE, 기능추가

#207 [BE] 다른유저 정보 조회
  server/db/userQueries.js
  server/middlewares/otherInfo.js
Labels: BE, 기능추가

#209 [BE] 검색 쿼리 수정 - #189
  server/db/searchQueries.js
Labels: BE, 수정

#212 [FE] 소셜 페이지 디자인 전체 수정
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Dashboard/MainCard/components/CardPanel.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
  client/src/pages/social.tsx
  client/src/recoil/atoms/SocialAtom.tsx
  client/src/styles/wrapper.tsx
  client/src/types/dashborad.types.tsx
  client/tailwind.config.js
Labels: FE, 기능추가, 레이아웃

#213 [FE] 설정 모달 전체 수정
  client/src/features/User/SwithToggle.tsx
  client/src/features/User/UserModal.tsx
Labels: FE, 레이아웃, 리펙토링

#214 [FE] 노드 크기 수정
  server/routes/graphs.js
Labels: BE, 레이아웃

#215 [BE] 노드 인덱스 수정
  server/routes/graphs.js
Labels: BE, 레이아웃

#216 [BE] 업로드 태그추출 에러처리
  server/middlewares/cardTag.js
  server/middlewares/recomUser.js
  server/routes/uploads.js
  server/services/taglist.js
Labels: BE, 에러 핸들링

#219 [FE] 소셜 상세 모달 디자인 수정
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Social/components/CardDetail.tsx
Labels: FE, 레이아웃

#220 [FE] API 리턴값 수정
  client/src/axios/GET.tsx
  client/src/axios/POST.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
  client/src/recoil/atoms/SocialAtom.tsx
Labels: FE, 리펙토링, 에러 핸들링

#221 [BE] 친구 업데이트 디폴트 계정 추가
  server/middlewares/follow.js
Labels: BE, 기능추가

#225 [FE] 소셜 페이지 디자인 수정
  client/src/features/Dashboard/MainCard/components/CardPanel.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/pages/social.tsx
Labels: FE, 레이아웃

#230 [FE] POST 응답 수정
  client/src/axios/POST.tsx
  client/src/features/Dashboard/MainGraph/components/Graph/setCategories.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/Social/components/CardDetail.tsx
  server/middlewares/cloneCard.js
  server/routes/graphs.js
Labels: FE, BE, 에러 핸들링

#231 [BE] Rollback
  server/routes/graphs.js
Labels: BE

#232 fix : auth error
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/User/GoogleLoginBtn.tsx
  client/src/features/User/GoogleLogoutBtn.tsx
  client/src/features/User/LogoutBtn.tsx
  client/src/features/User/UserModal.tsx
  client/src/pages/_app.tsx
  client/src/pages/api/auth/[...nextauth].ts
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/logout.tsx
  client/src/pages/signup.tsx
  server/middlewares/userProfile.js
  server/routes/login.js
  server/routes/signup.js
Labels: BE, 수정

#233 [FE] 검색페이지 css 수정, API 경로 수정
  client/src/axios/DELETE.tsx
  client/src/axios/GET.tsx
  client/src/axios/POST.tsx
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/components/AlarmModal.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/pages/search.tsx
Labels: FE, 수정

#236 [FE] 유저 모달 토글 on/off 수정
  client/src/features/User/SwithToggle.tsx
Labels: FE, 수정

#237 [BE] 검색 페이지네이션
  client/src/pages/search.tsx
  server/db/searchQueries.js
  server/routes/search.js
Labels: BE, 기능추가

#239 [FE] api 함수 통일, websocket 삭제
  client/package-lock.json
  client/package.json
  client/src/axios/DELETE.tsx
  client/src/axios/GET.tsx
  client/src/axios/PATCH.tsx
  client/src/axios/POST.tsx
  client/src/features/Dashboard/MainGraph/components/OnClickEvent/MouseDown.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
  client/src/features/User/UserModal.tsx
  client/src/features/User/UseronlyButton.tsx
  client/src/features/User/WithdrawalBtn.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/search.tsx
  client/src/pages/signup.tsx
Labels: FE, 리펙토링

#240 [BE] 태그리스트 DB로 변경
  server/index.js
  server/package.json
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/services/generate.js
  server/services/taglist.js
Labels: BE, 기능추가, 리펙토링

#241 [FE] 검색페이지 카드 상세 css적용
  client/src/features/Search/CardModal.module.css
  client/src/features/Search/CardModal.tsx
  server/middlewares/auth-middleware.js
Labels: FE

#242 [FE] type, atom, ImageUpload 컴포넌트 분리
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/ImageUpload/ResizeImage.tsx
  client/src/features/ImageUpload/UploadImagesToS3.tsx
  client/src/features/ImageUpload/hooks/useUploadImagesToS3.tsx
  client/src/features/MainGraph/components/Loading/UploadLoading.tsx
  client/src/features/Search/Card.tsx
  client/src/features/Search/SearchBar.tsx
  client/src/pages/dashboard/index.tsx
  client/src/recoil/atoms/ImageUploadAtom.tsx
  client/src/recoil/atoms/MainGraphAtom.tsx
  client/src/types/card.types.tsx
  client/src/types/imgUpload.types.tsx
  client/src/types/search.types.tsx
  client/src/types/user.types.tsx
Labels: FE, 리펙토링

#244 [FE] 소셜 페이지 디자인 수정 및 코드 정리
  client/src/features/Dashboard/MainGraph/components/Loading/UploadLoading.tsx
  client/src/features/MainGraph/components/Loading/UploadLoading.tsx
  client/src/features/Search/CardModal.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
  client/src/features/User/SwithToggle.tsx
  client/src/features/User/UserModal.tsx
  client/src/pages/search.tsx
  client/src/types/social.types.tsx
  server/db/cardQueries.js
  server/middlewares/cardInfo.js
Labels: FE, 기능추가, 레이아웃, 리펙토링

#245 [FE] 랜딩, 회원가입, 로그인 페이지 디자인 수정, 코드 정리 및 라우팅 추가
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Dashboard/MainCard/components/CardDetail.tsx
  client/src/features/Dashboard/MainCard/components/DuplicateCardBtn.tsx
  client/src/features/Dashboard/UserPanal/components/FollowBtn.tsx
  client/src/features/Dashboard/UserPanal/components/GraphEditBtn.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/Search/Card.tsx
  client/src/features/Search/CardModal.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Users.tsx
  client/src/features/User/LoginBtn.tsx
  client/src/features/User/LogoutBtn.tsx
  client/src/features/User/SignupButton.tsx
  client/src/features/User/UserModal.tsx
  client/src/features/User/WithdrawalBtn.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/logout.tsx
  client/src/pages/search.tsx
  client/src/pages/signup.tsx
Labels: FE, 레이아웃, 리펙토링
