Repository insight-LINK/insightLINK, pull requests merged in 2023-07, with the labels that each got.

#249 [BE] 알림기능
  server/db/alarmQueries.js
  server/middlewares/follow.js
  server/routes/notification.js
Labels: BE, 기능추가

#250 [FE/BE] 대시보드 페이지네이션
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Dashboard/MainCard/components/CardPanel.tsx
  client/src/features/Dashboard/MainCard/hook/useCard.tsx
  client/src/types/dashborad.types.tsx
  server/db/searchQueries.js
  server/db/tagQueries.js
  server/middlewares/cardTag.js
  server/routes/search.js
Labels: FE, BE, 기능추가, 수정

#251 [BE] 태그리스트 로직 변경
  client/next.config.js
  client/package.json
  client/src/features/Dashboard/MainGraph/components/Graph/Graph.tsx
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  server/index.js
  server/package.json
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/services/generate.js
  server/services/taglist.js
Labels: BE, 기능추가

#253 [FE] 이미지 업로드 비동기 오류 처리
  client/src/features/Dashboard/MainCard/components/Card.tsx
  client/src/features/Dashboard/MainCard/components/CardPanel.tsx
  client/src/features/ImageUpload/ImageUpload.tsx
  client/src/features/ImageUpload/hooks/useUploadImagesToS3.tsx
  client/src/features/Social/components/Feeds.tsx
  client/src/types/dashborad.types.tsx
Labels: FE, 리펙토링, 에러 핸들링

#254 [BE] 프롬프트 및 OpenAI 모델 변경
  client/src/features/ImageUpload/ImageUpload.tsx
  server/routes/uploads.js
  server/services/generate.js
Labels: BE, 기능추가

#255 [BE] 태그리스트 N개 확장, 유저별 태그리스트 적용
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/services/generate.js
Labels: BE

#256 [FE/BE] 카카오톡 공유하기 링크
  client/src/axios/dashBoardApi.tsx
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  server/index.js
  server/routes/graphs.js
  server/routes/userName.js
Labels: FE, BE, 기능추가

#257 feat: 카카오톡 공유하기 링크 수정 - #143
  client/src/features/Dashboard/components/NavBar.tsx
Labels: FE, 수정

#258 [FE] Onboarding 페이지 추가
  client/src/features/Dashboard/MainCard/components/CardDetail.tsx
  client/src/features/Dashboard/UserPanal/components/UserInfo.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/Social/components/CardDetail.tsx
  client/src/features/Social/components/Friends.tsx
  client/src/features/Social/components/Onboarding.tsx
  client/src/features/Social/components/User.tsx
  client/src/features/Social/components/Users.tsx
  client/src/features/User/UserModal.tsx
  client/src/pages/search.tsx
  client/src/pages/social.tsx
  client/src/recoil/atoms/LoginStateAtom.tsx
  client/src/recoil/atoms/SocialAtom.tsx
  client/src/types/social.types.tsx
Labels: FE, 기능추가, 레이아웃

#259 [BE] 유저별 태그리스트 저장
  server/routes/graphs.js
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/services/generate.js
Labels: BE, 기능추가

#260 [BE] 복제시 알림
  server/middlewares/cloneCard.js
  server/routes/notification.js
Labels: BE, 수정

#262 [FE] PWA 설정
  client/package.json
  client/public/icons/icon-128x128.png
  client/public/icons/icon-144x144.png
  client/public/icons/icon-152x152.png
  client/public/icons/icon-192x192.png
  client/public/icons/icon-384x384.png
  client/public/icons/icon-48x48.png
  client/public/icons/icon-512x512.png
  client/public/icons/icon-72x72.png
  client/public/icons/icon-96x96.png
  client/public/manifest.json
  client/public/service-worker.js
  client/public/splashscreens/iOS/10.2__iPad_landscape.png
  client/public/splashscreens/iOS/10.2__iPad_portrait.png
  client/public/splashscreens/iOS/10.5__iPad_Air_landscape.png
  client/public/splashscreens/iOS/10.5__iPad_Air_portrait.png
  client/public/splashscreens/iOS/10.9__iPad_Air_landscape.png
  client/public/splashscreens/iOS/10.9__iPad_Air_portrait.png
  client/public/splashscreens/iOS/11__iPad_Pro__10.5__iPad_Pro_landscape.png
  client/public/splashscreens/iOS/11__iPad_Pro__10.5__iPad_Pro_portrait.png
  client/public/splashscreens/iOS/12.9__iPad_Pro_landscape.png
  client/public/splashscreens/iOS/12.9__iPad_Pro_portrait.png
  client/public/splashscreens/iOS/4__iPhone_SE__iPod_touch_5th_generation_and_later_landscape.png
  client/public/splashscreens/iOS/4__iPhone_SE__iPod_touch_5th_generation_and_later_portrait.png
  client/public/splashscreens/iOS/8.3__iPad_Mini_landscape.png
  client/public/splashscreens/iOS/8.3__iPad_Mini_portrait.png
  client/public/splashscreens/iOS/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_landscape.png
  client/public/splashscreens/iOS/9.7__iPad_Pro__7.9__iPad_mini__9.7__iPad_Air__9.7__iPad_portrait.png
  client/public/splashscreens/iOS/iPhone_11_Pro_Max__iPhone_XS_Max_landscape.png
  client/public/splashscreens/iOS/iPhone_11_Pro_Max__iPhone_XS_Max_portrait.png
  client/public/splashscreens/iOS/iPhone_11__iPhone_XR_landscape.png
  client/public/splashscreens/iOS/iPhone_11__iPhone_XR_portrait.png
  client/public/splashscreens/iOS/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_landscape.png
  client/public/splashscreens/iOS/iPhone_13_mini__iPhone_12_mini__iPhone_11_Pro__iPhone_XS__iPhone_X_portrait.png
  client/public/splashscreens/iOS/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_landscape.png
  client/public/splashscreens/iOS/iPhone_14_Plus__iPhone_13_Pro_Max__iPhone_12_Pro_Max_portrait.png
  client/public/splashscreens/iOS/iPhone_14_Pro_Max_landscape.png
  client/public/splashscreens/iOS/iPhone_14_Pro_Max_portrait.png
  client/public/splashscreens/iOS/iPhone_14_Pro_landscape.png
  client/public/splashscreens/iOS/iPhone_14_Pro_portrait.png
  client/public/splashscreens/iOS/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_landscape.png
  client/public/splashscreens/iOS/iPhone_14__iPhone_13_Pro__iPhone_13__iPhone_12_Pro__iPhone_12_portrait.png
  client/public/splashscreens/iOS/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_landscape.png
  client/public/splashscreens/iOS/iPhone_8_Plus__iPhone_7_Plus__iPhone_6s_Plus__iPhone_6_Plus_portrait.png
  client/public/splashscreens/iOS/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_landscape.png
  client/public/splashscreens/iOS/iPhone_8__iPhone_7__iPhone_6s__iPhone_6__4.7__iPhone_SE_portrait.png
  client/public/workbox-7c2a5a06.js
  client/src/pages/_app.tsx
  client/src/pages/_document.tsx
Labels: FE, 기능추가, 리펙토링

#263 [FE] 회원가입, 로그인 디자인 수정
  client/src/features/Dashboard/MainGraph/components/Graph/ChartDefaultOptions.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
Labels: FE, 레이아웃

#264 [BE] 그래프, 프롬프트 변경
  client/next.config.js
  client/src/features/Dashboard/MainGraph/components/Graph/Graph.tsx
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  server/db/graphQueries.js
  server/routes/graphs.js
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/services/generate.js
  server/services/jsonUtils.js
  server/services/taglist.js
Labels: BE, 기능추가

#266 [FE] 검색페이지 카드 상세 이미지 안뜨는 오류 해결 - #265
  client/src/features/Search/CardModal.tsx
Labels: FE, 수정

#267 [에러 수정] api/share 에러
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  server/routes/graphs.js
  server/routes/userName.js
Labels: 에러 핸들링

#268 [FE] 검색페이지 CSS 변경
  client/package.json
  client/src/features/Search/CardModal.tsx
  client/src/features/Search/SearchBar.tsx
  client/src/pages/search.tsx
Labels: FE

#269 [FE] 카드 상세 scroll css - #268
  client/src/features/Search/CardModal.module.css
  client/src/features/Search/CardModal.tsx
  client/src/styles/globals.css
Labels: FE

#273 [BE] 비밀번호 암호화 - #272
  server/package.json
  server/routes/login.js
  server/routes/signup.js
Labels: BE, 기능추가

#271 [FE]프로필 클릭 시, 에러 고침 - #81
  client/next.config.js
Labels: 에러 핸들링

#274 [BE] 그래프 쿼리 수정
  server/routes/graphs.js
  server/routes/uploads.js
Labels: BE, 수정

#278 [FE] 로그인 여부에 따른 페이지 전환 - #276
  client/src/pages/login.tsx
  client/src/pages/logout.tsx
  client/src/pages/search.tsx
  client/src/pages/signup.tsx
  client/src/pages/social.tsx
  client/src/pages/useronly.tsx
Labels: FE

#279 [FE] 로그인 여부에 따른 데시보드 페이지 전환 - #276
  client/src/features/Dashboard/MainGraph/hooks/useGraph.tsx
  client/src/pages/dashboard/index.tsx
Labels: FE

#280 [BE] 간선 연결/제거 추가, 그래프 코드 모듈화
  client/src/features/Dashboard/MainCard/components/CardDetail.tsx
  server/db/connectQueries.js
  server/middlewares/graphUtils.js
  server/routes/graphs.js
  server/routes/uploads.js
  server/routes/z_dummy.js
  server/services/generate.js
  server/services/naverOCR.js
Labels: BE, 기능추가

#284 [FE] Add 공유하기 페이지 및 대시보드 검색창 css 수정 - #143
  client/src/features/Dashboard/UserPanal/components/SearchBar.tsx
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  client/src/features/Dashboard/components/NavBar.tsx
  client/src/features/Search/SearchBar.tsx
  client/src/features/User/LoginBtn.tsx
  client/src/features/User/SignupButton.tsx
  client/src/pages/index.tsx
Labels: FE

#286 [BE] 태그개수 변경
  server/routes/uploads.js
  server/services/generate.js
  server/services/jsonUtils.js
  server/services/naverOCR.js
Labels: BE, 수정

#289 [FE] 공유하기 그래프 추가, 로그아웃 시, 리코일 정보 제거 - #143
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  client/src/features/User/LogoutBtn.tsx
  client/src/pages/logout.tsx
Labels: FE, 에러 핸들링

#290 데시보드 페이지 에러 및 graph middleware에러 로그 추가 - #143
  client/src/features/Dashboard/components/Dashboardlayout.tsx
  server/middlewares/auth-middleware.js
Labels: FE

#297 [FE] 소셜 친구 추가 시 컴포넌트 변경되지 않는 이슈 수정
  client/src/features/Social/components/User.tsx
  client/src/pages/social.tsx
Labels: FE, 에러 핸들링

#298 [FE] 소셜 친구 추가 시 컴포넌트 변경되지 않는 이슈 수정
  client/src/features/Social/components/User.tsx
  client/src/pages/social.tsx
Labels: FE, 에러 핸들링
